services:
  backend:
    image: bot_backend
    container_name: zakaz
    depends_on:
      - postgres
    ports:
      - "8080-8888:8080-8888"
    environment:
      BOT_TOKEN: "6892595918:AAEGUZcYYZu3ZHL0d8iPKXFxOOK5chiMfY4"
      BOT_USERNAME: "QuestionEveryDay_bot"
      SPREADSHEETID: "181N49nhhplDr52neZNqW_2O4d4Q9QwfXK4oEUsdt1l4"
      POSTGRES_DB: "questionbot"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "a785410a"
    build:
      context: image/
    restart: always
  postgres:
    image: postgres
    container_name: postgres_bot
    hostname: postgres
    environment:
      POSTGRES_DB: "questionbot"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "a785410a"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "3050:5432"
    restart: always
